#!/bin/bash

WALL_DIR="$HOME/wallpaper"

# Load pywal colors
source "$HOME/.cache/wal/colors.sh"

# Ensure swww daemon is running
if ! pidof swww-daemon >/dev/null; then
    swww-daemon &
    sleep 0.5
fi

GRID_THEME="
* {
    font: \"JetBrainsMono Nerd Font 11\";
}

window {
    width: 820px;
    height: 700px;
    anchor: center;
    location: center;

    border: 2px;
    border-radius: 22px;
    border-color: ${color4};

    background-color: ${background}66;

    padding: 18px;

    transparency: \"real\";
}

mainbox {
    background-color: transparent;
    spacing: 14px;
    children: [ inputbar, listview ];
}

inputbar {
    padding: 12px 16px;
    border-radius: 16px;
    background-color: ${color0}44;
    children: [ prompt, entry ];
}

prompt {
    enabled: true;
    text-color: ${color4};
    background-color: transparent;
    margin: 0px 8px 0px 0px;
}

entry {
    placeholder: \"Search wallpaper...\";
    placeholder-color: ${foreground}66;
    text-color: ${foreground};
    background-color: transparent;
}

listview {
    columns: 3;
    lines: 2;
    flow: horizontal;

    fixed-height: true;
    fixed-columns: true;

    cycle: false;
    scrollbar: false;

    spacing: 16px;

    background-color: transparent;
}

element {
    orientation: vertical;

    padding: 10px;
    spacing: 10px;

    border-radius: 18px;

    background-color: transparent;
}

element selected.normal {
    background-color: ${color4}33;
    border: 2px;
    border-color: ${color4};
}

element selected.active {
    background-color: ${color4}33;
    border: 2px;
    border-color: ${color4};
}

element selected.urgent {
    background-color: ${color4}33;
    border: 2px;
    border-color: ${color4};
}

element-icon {
    size: 210px;

    horizontal-align: 0.5;
    vertical-align: 0.5;

    border-radius: 14px;

    background-color: transparent;
}

element-text {
    horizontal-align: 0.5;

    text-color: ${foreground}dd;

    background-color: transparent;
}
"

SELECTED=$(
for img in "$WALL_DIR"/*; do
    [[ "$img" =~ \.(jpg|jpeg|png|webp|PNG|JPG)$ ]] || continue
    printf "%s\0icon\x1f%s\n" "$(basename "$img")" "$img"
done | rofi \
    -dmenu \
    -i \
    -show-icons \
    -theme-str "$GRID_THEME" \
    -p "" \
    -name "wallpaper-picker"
)

if [ -n "$SELECTED" ]; then
    awww img "$WALL_DIR/$SELECTED" \
        --transition-type wipe \
        --transition-duration 1.3

    wal -n -i "$WALL_DIR/$SELECTED"
    pkill waybar
    waybar
fi
