background {
    monitor =
    path = /home/dibas/wallpaper/wall5.png
    blur_passes = 3
    blur_size = 3
    brightness = 0.5
}
input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgba(2755AC55)
    inner_color = rgba(00000088)
    font_color = rgb(c9d4ea)
    dots_size = 0.3
    dots_spacing = 0.2
    dots_center = true
    position = 0, -100
    halign = center
    valign = center
}
label {
    monitor =
    text = cmd[update:1000] echo "$(LC_TIME=en_US.UTF-8 date +"%I:%M %p")"
    font_size = 100
    font_family = Rounded M+ 1c Bold
    position = 0, 100
    halign = center
    valign = center
}
